
== Derived types

Derived types are types defined by combining already defined types (primitive or derived
as well) with the constructs provided by the C-like _typedef_ syntax described in this
section.

In order to add types to a mould set, their definitions are to be supplied to the
<<typedef,*typedef*>>( ) or to the <<ftypedef,*ftypedef*>>( ) method. The former accepts
definitions in a string, while the latter accepts the name of a file containing them.

=== Typedef methods

[[typedef]]
* *typedef* (_ms_, _defs_) +
-> _name~1~_, _name~2~_, _..._ +
 +
Parses the string _defs_ and adds to the mould set _ms_ the types it defines.
Returns the list of names of the types.

'''
[[ftypedef]]
* *ftypedef* (_ms_, _filename_) +
-> _name~1~_, _name~2~_, _..._ +
 +
Same as <<typedef,*typedef*>>( ), but it gets the type definitions from a file instead.


Multiple typedefs can be bundled in the same string or file.

Definitions can contain one-line Lua comments (`-- ...`), C comments (`/* ... */`) and
C++ comments (`// ...`). They can also contain lines starting with a `#`, like for example
C preprocessor directives. All this is stripped by LuaMoulds before parsing the typedefs.

The syntax supports the *struct* and *union* constructs, *arrays*, and nesting.

Typedefs, and fields in structs and unions, can be separated by just one or more
whitespaces (sequences of spaces, tabs and newlines), but the separators `,` and `;`
may optionally be used. 

<<<

=== Type declaration syntax

Below is the PEG description of the type declaration syntax. 

----
typedecl       <-  'typedef' sp+ basetype sp+ Name array* sep?
basetype       <-  'void' / structorunion / Type
array          <-  sp* '[' sp* Size sp* ']' 
structorunion  <-  ('struct' / 'union') sp* fieldlist
fieldlist      <-  '{' sp* field (sep field)* sep? '}'
field          <-  basetype sp+ FieldName array?
sp             <-  ' ' / '\t' / '\n'
sep            <-  (sp* (',' / ';') sp*) / sp+
----

`Size` is a positive integer, while `Name`, `FieldName` and `Type` are identifiers
composed only of letters, digits and underscores, and not starting with a digit
(`Type` must be the name of an already defined type, primitive or derived as well).

<<<
